#!/usr/bin/node

const { execSync } = require("child_process");

if (!process.argv[2] || isNaN(process.argv[2])) {
    console.log("usage: darkify 0.5")
    process.exit(1)
}

let brightness

if (process.argv[2]) {
    if (process.argv[2] >= 1) brightness = 1
    else if (process.argv[2] <= 0) brightness = 0.1
    else brightness = process.argv[2]
}

let monitors = execSync("xrandr --listmonitors | awk '{print $4}'").toString().trim().split("\n")

monitors.map(monitor => {
    if (brightness !== undefined) {
        execSync(`xrandr --output ${monitor} --brightness ${brightness}`)
        console.log(`${monitor} brightness set to ${brightness}`)
    }
})